name: Update Meta for Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-meta:
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # or your preferred JDK version

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Run the Gradle task
      - name: Run updateMetaForDocker
        run: ./gradlew :updateMetaForDocker
