name: Update Meta for Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-meta:
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '22'
          cache: 'gradle'
          cache-dependency-path: | # optional
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties

      # Run the Gradle task
      - name: Run updateMetaForDocker
        run: ./gradlew :updateMetaForDocker
