name: Update Meta for Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      - name: Build
        run: |
          export JAVA_HOME=/usr/bin/java
          cp /root/tucik/backend/application.properties $pwd/application.properties
          cp /root/tucik/backend/tucik-e0058-firebase-adminsdk-fbsvc-930035d462.json $pwd/tucik-e0058-firebase-adminsdk-fbsvc-930035d462.json
          chmod +x gradlew
          ./gradlew assemble
          mv build/libs/tusa-0.0.1-SNAPSHOT.jar /root/tucik/backend/tucik-backend.jar
      - name: Refresh
        run: systemctl restart tucik-backend
