name: Update Meta for Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-meta:
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '22'
          cache: 'gradle'

      # Run the Gradle task
      - name: Run updateMetaForDocker
        run: ./gradlew :updateMetaForDocker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: invectys/tucik:latest
